[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node_modules/.bin/ts-node -r tsconfig-paths/register backend/src/main.ts"

[variables]
NODE_ENV = "production"
PORT = "3000"
