[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x"]

[phases.install]
cmds = [
  "npm ci --no-audit --no-fund",
  "cd backend && npm ci --no-audit --no-fund",
  "cd frontend && npm install --no-audit --no-fund"
]

[phases.build]
cmds = [
  "cd backend && npm run build",
  "cd frontend && npm run build"
]

[start]
cmd = "cd backend && node dist/main"

[variables]
NODE_ENV = "production"
PORT = "3000"
HOSTNAME = "0.0.0.0"
