[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmd = "npm ci"

[phases.build]
cmd = "npm run build"

[phases.start]
cmd = "cd backend && node dist/main.js"

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"
CI = "true"
