[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x"]

[phases.install]
cmds = ["npm ci", "cd backend && npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node_modules/.bin/nest start"

[variables]
NODE_ENV = "production"
PORT = "3000"
